Add IPAM migration unit tests
projectcalico/calicoctl pull request #2199
Opened 2020-10-05 20:26 UTC by mgleung

## Description
Follow up to https://github.com/projectcalico/calicoctl/pull/2186 to add some UTs

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

2020-10-13 17:47 UTC, caseydavenport requested changes
A couple minor comments, but overall looks good.

Do we need a test for per-node FelixConfiguration / BGPConfiguration as well?

2020-10-13 17:47 UTC, caseydavenport commented on calicoctl/commands/datastore/migrate/migrateipam_test.go
> +		// Check that the IPAM handle attributes were changed correctly
same here

2020-10-15 23:07 UTC, mgleung commented
Forgot to even add the handling for the BGP configs. Added that and the appropriate tests for that and the felix configs.

2020-10-19 17:58 UTC, caseydavenport approved these changes

2020-10-19 18:05 UTC, merged