Build all architectures for calicoctl
projectcalico/calicoctl pull request #2313
Opened 2021-04-20 22:35 UTC by mgleung

## Description

Ensures that all of the architectures that we support are built and uploaded on each release for the calicoctl utility. Fixes https://github.com/projectcalico/calicoctl/issues/2269

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

2021-04-20 22:46 UTC, caseydavenport approved these changes

2021-04-21 15:19 UTC, Brian-McM approved these changes

2021-04-21 15:23 UTC, Brian-McM commented on Makefile
> +VALIDARCHES=$(patsubst Dockerfile.%,%,$(wildcard Dockerfile.*))
This needs to be above the include for the common makefile otherwise the targets in the common makefile won't be created for all the valid arches

2021-04-21 15:24 UTC, Brian-McM requested changes
Could you please move VALIDARCHES above the include for the common makefile

2021-04-21 15:29 UTC, Brian-McM commented
So my other comment is slightly wrong, what you need to do is set `EXCLUDEARCH` to empty before the common makefile include:
```
ARCHES ?= $(patsubst docker-image/Dockerfile.%,%,$(wildcard docker-image/Dockerfile.*))

# Some repositories keep their Dockerfile(s) in the root directory instead of in
# the 'docker-image' subdir. Make sure ARCHES gets filled in either way.
ifeq ($(ARCHES),)
    ARCHES=$(patsubst Dockerfile.%,%,$(wildcard Dockerfile.*))
endif

# list of arches *not* to build when doing *-all
#    until s390x works correctly
EXCLUDEARCH ?= s390x
VALIDARCHES = $(filter-out $(EXCLUDEARCH),$(ARCHES))
```
^^ that's in the common Makefile. The "sub" targets that are created on the include require the VALIDARCHES be set before the include.

2021-04-21 21:50 UTC, Brian-McM approved these changes

2021-04-21 21:50 UTC, merged